import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import { SessionProvider } from "next-auth/react";


import Footer from "@/component/Footer";
import NextAuthProviders from "@/Providers/NextAuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <NextAuthProviders>
         <Navbar></Navbar>
       
        
     
         <main className="flex-1">{children}</main>
         </NextAuthProviders>
         <Footer></Footer>
       
         
        
      </body>
    </html>
  );
}
